---
title: "Scalogram_vignette"
author: "Authors"
date: "2023-05-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Reading the data

```{r}
library(raster)
library(sf)
library(Scalogram)
raster <-raster("X:\\akash\\PROJECTS\\Duda\\data\\all_data\\MOD_CumDHI_GCS.tif")
# Load the shapefile
shapefile_file <- "X:\\akash\\PROJECTS\\Duda\\data\\all_data\\Plots.shp"
shapefile <- st_read(shapefile_file)

plot(raster)
plot(shapefile, add = TRUE)   # shapefile[,1]


```

## Extracting raster from shapefile over a range of extent

```{r}
extent <- c(3,5,7,9,11,21,31,41,51,61,71,81,91,101)

data <- scalogram.extract_by_extent("X:\\akash\\PROJECTS\\Duda\\data\\all_data\\MOD_CumDHI_GCS.tif", "X:\\akash\\PROJECTS\\Duda\\data\\all_data\\Plots.shp", extent)

head(data)
```

## Estimating spatial area covered by each extent(sq. m.)

```{r}
area<-extent^2*(3*3)
area 
```

## Convert the input parameters from list to matrices 
```{r}
#extent <- data.frame(extent)
area<-as.matrix(data.frame(area))

#y <- data.frame(data[,37:50])
data<-as.matrix(data)

```



## Plot 

```{r}

scalogram.plot_trendline(data[1,],area,degree=3)   # y[1,] means for point 1



```

## Calculating and plotting first derivative

```{r}
deriv <- scalogram.first_derivative(data[1,],area,3)  # Row 1: data[1,]
#plot(area,deriv )

plot(area,deriv, type = "p", pch = 16, col = "blue", ylim = c(min(deriv), max(deriv)), xlab = "Area", ylab = "1st Derivative")

# Add a line plot
lines(area,deriv, type = "l", col = "red", lwd = 2)

# Add labels for the points
#text(area,deriv, labels = deriv, col = "black")
```
## Calculating and plotting critical points

```{r}


critical_points <- scalogram.critical_points(data, area, degree=3)

head(critical_points)

```

```{r}

deriv <- scalogram.first_derivative(data[1,], area, 3)

fitted_curve <- lm(deriv ~ poly(area, degree = 3, raw = TRUE))
coefficients <- coef(fitted_curve)

poly_eq <- function(x) {
  y <- (as.double(coefficients[[1]])) + (as.double(coefficients[[2]])) * x^1 +
    (as.double(coefficients[[3]])) * x^2 + (as.double(coefficients[[4]]))
 return(y)
  }

cat("critical Points: ",critical_points[1,])

plot(poly_eq, from = min(area), to = max(area), xlab = "x", ylab = "y")
points(critical_points[1,], poly_eq(critical_points[1,]), col = "red", pch = 16)
abline(a = 0, b = 0, col = "green")
```


## Calculating scalogram habitat measures

```{r}
## 1. Intercept

intercept <- array()

for (i in 1:nrow(data)) {
  row <- data[i, ]
  # Perform operations on the row
  # Access individual elements using row$column_name or row[["column_name"]]
  value <- scalogram.fit_polynomial(row,area,3)
  # Store the value in the list
  intercept[i] <- value
}

#print(intercept)


## 2. Min

min <- array()

for (i in 1:nrow(data)) {
  row <- data[i, ]
  # Perform operations on the row
  # Access individual elements using row$column_name or row[["column_name"]]
  value <- scalogram.calculate_min(row)
  # Store the value in the list
  min[i] <- value
}

#print(min)

## 3. Min_ext

min_ext <- array()

for (i in 1:nrow(data)) {
  row <- data[i, ]
  # Perform operations on the row
  # Access individual elements using row$column_name or row[["column_name"]]
  value <- scalogram.calculate_min_extent(row,area)
  # Store the value in the list
  min_ext[i] <- value
}

#print(min_ext)

## 4. Max_ext

max_ext <- array()

for (i in 1:nrow(data)) {
  row <- data[i, ]
  # Perform operations on the row
  # Access individual elements using row$column_name or row[["column_name"]]
  value <- scalogram.calculate_max_extent(row,area)
  # Store the value in the list
  max_ext[i] <- value
}

#print(max_ext)

## 5. Max

max <- array()

for (i in 1:nrow(data)) {
  row <- data[i, ]
  # Perform operations on the row
  # Access individual elements using row$column_name or row[["column_name"]]
  value <- scalogram.calculate_max(row)
  # Store the value in the list
  max[i] <- value
}

#print(max)

## 6. Range

range <- array()

for (i in 1:nrow(data)) {
  row <- data[i, ]
  # Perform operations on the row
  # Access individual elements using row$column_name or row[["column_name"]]
  value <- scalogram.calculate_range(row)
  # Store the value in the list
  range[i] <- value
}

#print(range)


## 7. CV

cv <- array()

for (i in 1:nrow(data)) {
  row <- data[i, ]
  # Perform operations on the row
  # Access individual elements using row$column_name or row[["column_name"]]
  value <- scalogram.calculate_cv(row)
  # Store the value in the list
  cv[i] <- value
}


#print(cv)

## 8. max_slope of 1st derivative

max_slope <- array()

for (i in 1:nrow(data)) {
  row <- data[i, ]
  # Perform operations on the row
  # Access individual elements using row$column_name or row[["column_name"]]
  value <- scalogram.max_slope(row,area,3)
  # Store the value in the list
  max_slope[i] <- value
}


#print(max_slope)


## 9. Critical point of 1st derivative (y=0). 

critical_points <- scalogram.critical_points(data, area, degree=3)

cp_1 <- critical_points[,1]

cp_2 <- critical_points[,2]


## 10. intercept of 1st derivative

intercept_derivative <- array()

for (i in 1:nrow(data)) {
  row <- data[i, ]
  # Perform operations on the row
  # Access individual elements using row$column_name or row[["column_name"]]
  value <- scalogram.intercept(row,area,3)
  # Store the value in the list
  intercept_derivative[i] <- value
}

#print(intercept_derivative)

```
## plotting intercept of 1st derivative

```{r}

deriv <- scalogram.first_derivative(data[1,], area, 3)

fitted_curve <- lm(deriv ~ poly(area, degree = 3, raw = TRUE))
coefficients <- coef(fitted_curve)

poly_eq <- function(x) {
  y <- (as.double(coefficients[[1]])) + (as.double(coefficients[[2]])) * x^1 +
    (as.double(coefficients[[3]])) * x^2 + (as.double(coefficients[[4]]))
  return(y)
}

x1 <- seq(min(area), max(area), length.out = 100001)  # by = 1)
y1 <- poly_eq(x1)

intersection <- y1[which(diff(sign(x1)) != min(area))]

cat("critical Points: ",intersection[1])

plot(poly_eq, from = min(area), to = max(area), xlab = "x", ylab = "y")
points(intersection[1], poly_eq(intersection[1]), col = "red", pch = 16)
#abline(a = 0, b = 0, col = "green")

```


```{r}
final<-cbind(data,intercept, min,max,min_ext,max_ext,range,cv,max_slope,cp_1,cp_2,intercept_derivative)
head(final)
write.csv(final, "habitat_measure.csv")
```

